use_frameworks!
platform :ios, '8.0'

target 'HeliumKit' do
  pod "HeliumKit", :path => "../"
end

target 'Tests' do
  pod "HeliumKit", :path => "../"

  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
  #pod 'FBSnapshotTestCase', '~> 2.1'
  #pod 'Expecta+Snapshots', '~> 3.0'
end

#post_install do |installer|
#    target = installer.project.targets.find { |t| t.to_s == "Pods-Tests-Specta" }
#    if (target)
#        target.build_configurations.each do |config|
#            s = config.build_settings['FRAMEWORK_SEARCH_PATHS']
#            s = [ '$(inherited)' ] if s == nil;
#            s.push('$(PLATFORM_DIR)/Developer/Library/Frameworks')
#            config.build_settings['FRAMEWORK_SEARCH_PATHS'] = s
#        end
#        else
#        puts "WARNING: Pods-Tests-Specta target not found"
#    end
#end
