# reference: http://www.objc.io/issue-6/travis-ci.html

osx_image: xcode7.3
language: objective-c
node_js:
- 0.10
script:
- ./start_server.sh
- xctool test -workspace Example/HeliumKit.xcworkspace -scheme HeliumKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
# fix for https://github.com/travis-ci/travis-ci/issues/2836
before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
